---
- name: Create the admin user
  ansible.builtin.user:
    name: '{{ user.name }}'
    password: '{{ user.password }}'
    shell: '{{ user.shell }}'
    groups: '{{ user.groups }}'
    append: true
    update_password: on_create
