---
- name: Clone paru repository
  ansible.builtin.git:
    repo: '{{ paru.repo }}'
    dest: '{{ paru.install_dir }}'
    version: '{{ paru.git_branch }}'
    single_branch: true
    update: true
  become: true
  become_user: '{{ user.name }}'

# All the information related to paru will be obtained reading the file PKGBUILD
- name: Read the PKGBUILD file
  ansible.builtin.set_fact:
    fact_pkgbuild_info: "{{ lookup('file', pkgbuild_file) }}"

- name: Register the dependencies (for compilation and executing)
  ansible.builtin.set_fact:
    fact_depends:
      make: '{{ fact_pkgbuild_info | regex_findall("\nmakedepends=\(([^\n]+)\)") }}'
      exec: '{{ fact_pkgbuild_info | regex_findall("\ndepends=\(([^\n]+)\)") | first | split(" ") | list }}'

- name: Concatenate makedepends and depends vars
  ansible.builtin.set_fact:
    fact_all_depends: '{{ fact_depends.make + fact_depends.exec }}'

- name: Remove quotes from the dependencies values
  ansible.builtin.set_fact:
    fact_all_depends: "{{ fact_all_depends | regex_replace(\"'\", \"\") }}"

- name: Install paru dependencies
  community.general.pacman:
    name: '{{ fact_all_depends }}'
    state: present
    update_cache: true
