---
- name: Allow users on wheel group execute root commands
  ansible.builtin.lineinfile:
    path: '{{ file.sudoers }}'
    regexp: '^#\s*%wheel'
    line: '%wheel ALL=(ALL) ALL'
    state: present
