---
- name: Generate the fstab output
  ansible.builtin.command:
    cmd: '{{ command.genfstab }}'
  changed_when: false
  register: register_genfstab_output

- name: Write the output of the genfstab command to '{{ file.fstab }}'
  ansible.builtin.lineinfile:
    line: '{{ item }}'
    dest: '{{ file.fstab }}'
  with_items: '{{ register_genfstab_output.stdout_lines }}'
