---
- name: Edit locale.gen file
  ansible.builtin.lineinfile:
    path: '{{ file.locale_gen }}'
    regexp: '^#.*{{ locale }}'
    line: '{{ locale }}'
    state: present
  notify:
    - Generate locale
