---
- name: Check if the base system was already installed
  ansible.builtin.stat:
    path: '{{ file.release }}'
  register: base_system_installed

- name: Install the base system
  ansible.builtin.command: '{{ command.pacstrap }}'
  when: not base_system_installed.stat.exists
  changed_when: true
