---
- name: Check if the base system was already installed
  ansible.builtin.stat:
    path: '{{ file.release }}'
  register: register_base_system_stat

- name: Install the base system
  ansible.builtin.command:
    cmd: '{{ command.pacstrap }}'
  when: not register_base_system_stat.stat.exists
  changed_when: true
