---
- name: Set the time zone
  ansible.builtin.file:
    src: '{{ timezone_file }}'
    dest: '{{ file.localtime }}'
    state: link

- name: Check if the hardware clock was already synchronized
  ansible.builtin.stat:
    path: '{{ file.hardware_clock }}'
  register: register_hardware_clock_stat

- name: Set the hardware clock
  ansible.builtin.command:
    cmd: '{{ command.hwclock }}'
  when: not register_hardware_clock_stat.stat.exists
  changed_when: true
