---
- name: Generate locale
  ansible.builtin.command:
    cmd: '{{ command.locale_gen }}'
  changed_when: true

- name: Create the initramfs image
  ansible.builtin.command:
    cmd: '{{ command.mkinitcpio }}'
  changed_when: true

- name: Enable network manager
  ansible.builtin.service:
    name: '{{ network_manager.service }}'
    enabled: true
  delegate_to: arch_chroot
