---
# These tasks will ensure that both logical volumes have a size that is a multiple of the physical extent size (pesize)
# Also pesize will be subtracted to lv_home size to ensure that there's enough space for it on the volume group
- name: Convert lv_root size from GiB to MiB
  ansible.builtin.set_fact:
    lv_root_size: '{{ (lvm_partition.lv_root.size // lvm_partition.vg.pesize) * lvm_partition.vg.pesize }}'

# The size of lv_home will be the remaining space in the LVM partition after lv_root is created
- name: Calculate the remaining space on the partition to assign the lv_home size
  ansible.builtin.set_fact:
    lv_home_size: '{{ ((lvm_partition_size | int - lv_root_size | int - lvm_partition.vg.pesize) // (lvm_partition.vg.pesize)) * lvm_partition.vg.pesize }}'
