---
# Add 1 MiB to the boot partition size to ensure that the partition size accounts the 1 MiB reserved by GPT partition scheme
- name: Calculate the end of the boot partition
  ansible.builtin.set_fact:
    fact_boot_partition_end: '{{ boot_partition.size + 1 }}'

# If the boot mode is BIOS, the swap partition will start at the beginning of the disk
- name: Calculate the end of the swap partition
  ansible.builtin.set_fact:
    fact_swap_partition_end: '{{ swap_partition.size if fact_boot_mode == "bios" else fact_boot_partition_end | int + swap_partition.size }}'
