---
- name: Create the volume group
  community.general.lvg:
    vg: '{{ lvm_partition.vg.name }}'
    pvs: '{{ lvm_partition_device }}'
    pesize: '{{ lvm_partition.vg.pesize }}'

- name: Create logical volume for root filesystem
  community.general.lvol:
    vg: '{{ lvm_partition.vg.name }}'
    lv: '{{ lvm_partition.lv_root.name }}'
    size: '{{ fact_lv_root_size }}'

- name: Create logical volume for home filesystem
  community.general.lvol:
    vg: '{{ lvm_partition.vg.name }}'
    lv: '{{ lvm_partition.lv_home.name }}'
    size: '{{ fact_lv_home_size }}'
