---
boot_path: '/boot'
grub_cfg_path: '{{ boot_path }}/grub/grub.cfg'
grub_check_file: '{{ system_root ~ grub_cfg_path }}'

grub_efi_package_dependencies:
  - grub
  - efibootmgr
  - os-prober

grub_package_dependencies: >-
  {{ ['grub'] if boot_mode == 'bios' else grub_efi_package_dependencies }}

grub_mkconfig_command: '{{ chroot_command }} grub-mkconfig -o {{ grub_cfg_path }}'
grub_efi_install_command: '{{ chroot_command }} grub-install --target=x86_64-efi --efi-directory={{ boot_path }} --bootloader-id=GRUB'
grub_bios_install_command: '{{ chroot_command }} grub-install --target=i386-pc {{ disk }}'
grub_packages_command: '{{ chroot_command }} pacman -Sy --noconfirm {{ grub_package_dependencies | join(" ") }}'
