---
- name: Check the boot mode of the machine
  ansible.builtin.stat:
    path: '{{ efi_info_file }}'
  register: register_boot_mode_stat

- name: Register the machine boot mode
  ansible.builtin.set_fact:
    fact_boot_mode: '{{ "efi" if register_boot_mode_stat.stat.exists else "bios" }}'
