---
disk: /dev/sda  # (dynamic var)
partition_scheme: '{{ "msdos" if boot_mode == "bios" else "gpt" }}'  # Partition scheme used
standard_fstype: ext4  # Default filesystem format for the home and root partitions (dynamic var?)
parted_unit: MiB  # Unit used by parted to create partitions

boot_partition:
  number: 1
  size: 1024  # Size on MiB (dynamic var)
  fstype: vfat  # Filesystem of the boot partition
boot_partition_device: '{{ disk ~ boot_partition.number }}'

swap_partition:
  number: '{{ 1 if boot_mode == "bios" else 2 }}'
  size: 4096  # Size on MiB (dynamic var)
swap_partition_device: '{{ disk ~ swap_partition.number }}'

lvm_partition:
  number: '{{ 2 if boot_mode == "bios" else 3 }}'
  size: 100%  # (dynamic var)
  vg:
    name: vg0  # (dynamic var)
    pesize: 4  # Size of the physical extent
  lv_root:
    name: lv_root  # (dynamic var)
    size: 15360  # Size on MiB (dynamic var)
  lv_home:
    name: lv_home  # (dynamic var)
lvm_partition_device: '{{ disk ~ lvm_partition.number }}'
lvm_lv_home_device: '/dev/{{ lvm_partition.vg.name }}/{{ lvm_partition.lv_home.name }}'
lvm_lv_root_device: '/dev/{{ lvm_partition.vg.name }}/{{ lvm_partition.lv_root.name }}'
